export const allCountryCodes = {
  data: [
    {
      id: 1,
      country_short_name: "AF",
      phone_code: 93,
      country_code: "+93",
    },
    {
      id: 2,
      country_short_name: "AL",
      phone_code: 355,
      country_code: "+355",
    },
    {
      id: 3,
      country_short_name: "AL",
      phone_code: 213,
      country_code: "+213",
    },
    {
      id: 4,
      country_short_name: "AS",
      phone_code: 1684,
      country_code: "+1684",
    },
    {
      id: 5,
      country_short_name: "AD",
      phone_code: 376,
      country_code: "+376",
    },
    {
      id: 6,
      country_short_name: "AO",
      phone_code: 244,
      country_code: "+244",
    },
    {
      id: 7,
      country_short_name: "AI",
      phone_code: 1264,
      country_code: "+1264",
    },
    {
      id: 8,
      country_short_name: "AQ",
      phone_code: 0,
      country_code: "+0",
    },
    {
      id: 9,
      country_short_name: "AG",
      phone_code: 1268,
      country_code: "+1268",
    },
    {
      id: 10,
      country_short_name: "AR",
      phone_code: 54,
      country_code: "+54",
    },
    {
      id: 11,
      country_short_name: "AM",
      phone_code: 374,
      country_code: "+374",
    },
    {
      id: 12,
      country_short_name: "AW",
      phone_code: 297,
      country_code: "+297",
    },
    {
      id: 13,
      country_short_name: "AU",
      phone_code: 61,
      country_code: "+61",
    },
    {
      id: 14,
      country_short_name: "AT",
      phone_code: 43,
      country_code: "+43",
    },
    {
      id: 15,
      country_short_name: "AZ",
      phone_code: 994,
      country_code: "+994",
    },
    {
      id: 16,
      country_short_name: "BS",
      phone_code: 1242,
      country_code: "+1242",
    },
    {
      id: 17,
      country_short_name: "BH",
      phone_code: 973,
      country_code: "+973",
    },
    {
      id: 18,
      country_short_name: "BD",
      phone_code: 880,
      country_code: "+880",
    },
    {
      id: 19,
      country_short_name: "BB",
      phone_code: 1246,
      country_code: "+1246",
    },
    {
      id: 20,
      country_short_name: "BY",
      phone_code: 375,
      country_code: "+375",
    },
    {
      id: 21,
      country_short_name: "BE",
      phone_code: 32,
      country_code: "+32",
    },
    {
      id: 22,
      country_short_name: "BZ",
      phone_code: 501,
      country_code: "+501",
    },
    {
      id: 23,
      country_short_name: "BJ",
      phone_code: 229,
      country_code: "+229",
    },
    {
      id: 24,
      country_short_name: "BM",
      phone_code: 1441,
      country_code: "+1441",
    },
    {
      id: 25,
      country_short_name: "BT",
      phone_code: 975,
      country_code: "+975",
    },
    {
      id: 26,
      country_short_name: "BO",
      phone_code: 591,
      country_code: "+591",
    },
    {
      id: 27,
      country_short_name: "BA",
      phone_code: 387,
      country_code: "+387",
    },
    {
      id: 28,
      country_short_name: "BW",
      phone_code: 267,
      country_code: "+267",
    },
    {
      id: 29,
      country_short_name: "BV",
      phone_code: 0,
      country_code: "+0",
    },
    {
      id: 30,
      country_short_name: "BR",
      phone_code: 55,
      country_code: "+55",
    },
    {
      id: 31,
      country_short_name: "IO",
      phone_code: 246,
      country_code: "+246",
    },
    {
      id: 32,
      country_short_name: "BN",
      phone_code: 673,
      country_code: "+673",
    },
    {
      id: 33,
      country_short_name: "BG",
      phone_code: 359,
      country_code: "+359",
    },
    {
      id: 34,
      country_short_name: "BF",
      phone_code: 226,
      country_code: "+226",
    },
    {
      id: 35,
      country_short_name: "BI",
      phone_code: 257,
      country_code: "+257",
    },
    {
      id: 36,
      country_short_name: "KH",
      phone_code: 855,
      country_code: "+855",
    },
    {
      id: 37,
      country_short_name: "CM",
      phone_code: 237,
      country_code: "+237",
    },
    {
      id: 38,
      country_short_name: "CA",
      phone_code: 1,
      country_code: "+1",
    },
    {
      id: 39,
      country_short_name: "CV",
      phone_code: 238,
      country_code: "+238",
    },
    {
      id: 40,
      country_short_name: "KY",
      phone_code: 1345,
      country_code: "+1345",
    },
    {
      id: 41,
      country_short_name: "CF",
      phone_code: 236,
      country_code: "+236",
    },
    {
      id: 42,
      country_short_name: "TD",
      phone_code: 235,
      country_code: "+235",
    },
    {
      id: 43,
      country_short_name: "CL",
      phone_code: 56,
      country_code: "+56",
    },
    {
      id: 44,
      country_short_name: "CN",
      phone_code: 86,
      country_code: "+86",
    },
    {
      id: 45,
      country_short_name: "CX",
      phone_code: 61,
      country_code: "+61",
    },
    {
      id: 46,
      country_short_name: "CC",
      phone_code: 672,
      country_code: "+672",
    },
    {
      id: 47,
      country_short_name: "CO",
      phone_code: 57,
      country_code: "+57",
    },
    {
      id: 48,
      country_short_name: "KM",
      phone_code: 269,
      country_code: "+269",
    },
    {
      id: 49,
      country_short_name: "CG",
      phone_code: 242,
      country_code: "+242",
    },
    {
      id: 50,
      country_short_name: "CD",
      phone_code: 242,
      country_code: "+242",
    },
    {
      id: 51,
      country_short_name: "CK",
      phone_code: 682,
      country_code: "+682",
    },
    {
      id: 52,
      country_short_name: "CR",
      phone_code: 506,
      country_code: "+506",
    },
    {
      id: 53,
      country_short_name: "CI",
      phone_code: 225,
      country_code: "+225",
    },
    {
      id: 54,
      country_short_name: "HR",
      phone_code: 385,
      country_code: "+385",
    },
    {
      id: 55,
      country_short_name: "CU",
      phone_code: 53,
      country_code: "+53",
    },
    {
      id: 56,
      country_short_name: "CY",
      phone_code: 357,
      country_code: "+357",
    },
    {
      id: 57,
      country_short_name: "CZ",
      phone_code: 420,
      country_code: "+420",
    },
    {
      id: 58,
      country_short_name: "DK",
      phone_code: 45,
      country_code: "+45",
    },
    {
      id: 59,
      country_short_name: "DJ",
      phone_code: 253,
      country_code: "+253",
    },
    {
      id: 60,
      country_short_name: "DM",
      phone_code: 1767,
      country_code: "+1767",
    },
    {
      id: 61,
      country_short_name: "DO",
      phone_code: 1809,
      country_code: "+1809",
    },
    {
      id: 62,
      country_short_name: "TP",
      phone_code: 670,
      country_code: "+670",
    },
    {
      id: 63,
      country_short_name: "EC",
      phone_code: 593,
      country_code: "+593",
    },
    {
      id: 64,
      country_short_name: "EG",
      phone_code: 20,
      country_code: "+20",
    },
    {
      id: 65,
      country_short_name: "SV",
      phone_code: 503,
      country_code: "+503",
    },
    {
      id: 66,
      country_short_name: "GQ",
      phone_code: 240,
      country_code: "+240",
    },
    {
      id: 67,
      country_short_name: "ER",
      phone_code: 291,
      country_code: "+291",
    },
    {
      id: 68,
      country_short_name: "EE",
      phone_code: 372,
      country_code: "+372",
    },
    {
      id: 69,
      country_short_name: "ET",
      phone_code: 251,
      country_code: "+251",
    },
    {
      id: 70,
      country_short_name: "XA",
      phone_code: 61,
      country_code: "+61",
    },
    {
      id: 71,
      country_short_name: "FK",
      phone_code: 500,
      country_code: "+500",
    },
    {
      id: 72,
      country_short_name: "FO",
      phone_code: 298,
      country_code: "+298",
    },
    {
      id: 73,
      country_short_name: "FJ",
      phone_code: 679,
      country_code: "+679",
    },
    {
      id: 74,
      country_short_name: "FI",
      phone_code: 358,
      country_code: "+358",
    },
    {
      id: 75,
      country_short_name: "FR",
      phone_code: 33,
      country_code: "+33",
    },
    {
      id: 76,
      country_short_name: "GF",
      phone_code: 594,
      country_code: "+594",
    },
    {
      id: 77,
      country_short_name: "PF",
      phone_code: 689,
      country_code: "+689",
    },
    {
      id: 78,
      country_short_name: "TF",
      phone_code: 0,
      country_code: "+0",
    },
    {
      id: 79,
      country_short_name: "GA",
      phone_code: 241,
      country_code: "+241",
    },
    {
      id: 80,
      country_short_name: "GM",
      phone_code: 220,
      country_code: "+220",
    },
    {
      id: 81,
      country_short_name: "GE",
      phone_code: 995,
      country_code: "+995",
    },
    {
      id: 82,
      country_short_name: "DE",
      phone_code: 49,
      country_code: "+49",
    },
    {
      id: 83,
      country_short_name: "GH",
      phone_code: 233,
      country_code: "+233",
    },
    {
      id: 84,
      country_short_name: "GI",
      phone_code: 350,
      country_code: "+350",
    },
    {
      id: 85,
      country_short_name: "GR",
      phone_code: 30,
      country_code: "+30",
    },
    {
      id: 86,
      country_short_name: "GL",
      phone_code: 299,
      country_code: "+299",
    },
    {
      id: 87,
      country_short_name: "GD",
      phone_code: 1473,
      country_code: "+1473",
    },
    {
      id: 88,
      country_short_name: "GP",
      phone_code: 590,
      country_code: "+590",
    },
    {
      id: 89,
      country_short_name: "GU",
      phone_code: 1671,
      country_code: "+1671",
    },
    {
      id: 90,
      country_short_name: "GT",
      phone_code: 502,
      country_code: "+502",
    },
    {
      id: 92,
      country_short_name: "GN",
      phone_code: 224,
      country_code: "+224",
    },
    {
      id: 93,
      country_short_name: "GW",
      phone_code: 245,
      country_code: "+245",
    },
    {
      id: 94,
      country_short_name: "GY",
      phone_code: 592,
      country_code: "+592",
    },
    {
      id: 95,
      country_short_name: "HT",
      phone_code: 509,
      country_code: "+509",
    },
    {
      id: 96,
      country_short_name: "HM",
      phone_code: 0,
      country_code: "+0",
    },
    {
      id: 97,
      country_short_name: "HN",
      phone_code: 504,
      country_code: "+504",
    },
    {
      id: 98,
      country_short_name: "HK",
      phone_code: 852,
      country_code: "+852",
    },
    {
      id: 99,
      country_short_name: "HU",
      phone_code: 36,
      country_code: "+36",
    },
    {
      id: 100,
      country_short_name: "IS",
      phone_code: 354,
      country_code: "+354",
    },
    {
      id: 101,
      country_short_name: "IN",
      phone_code: 91,
      country_code: "+91",
    },
    {
      id: 102,
      country_short_name: "ID",
      phone_code: 62,
      country_code: "+62",
    },
    {
      id: 103,
      country_short_name: "IR",
      phone_code: 98,
      country_code: "+98",
    },
    {
      id: 104,
      country_short_name: "IQ",
      phone_code: 964,
      country_code: "+964",
    },
    {
      id: 105,
      country_short_name: "IE",
      phone_code: 353,
      country_code: "+353",
    },
    {
      id: 106,
      country_short_name: "IL",
      phone_code: 972,
      country_code: "+972",
    },
    {
      id: 107,
      country_short_name: "IT",
      phone_code: 39,
      country_code: "+39",
    },
    {
      id: 108,
      country_short_name: "JM",
      phone_code: 1876,
      country_code: "+1876",
    },
    {
      id: 109,
      country_short_name: "JP",
      phone_code: 81,
      country_code: "+81",
    },
    {
      id: 110,
      country_short_name: "GB",
      phone_code: 44,
      country_code: "+44",
    },
    {
      id: 111,
      country_short_name: "JO",
      phone_code: 962,
      country_code: "+962",
    },
    {
      id: 112,
      country_short_name: "KZ",
      phone_code: 7,
      country_code: "+7",
    },
    {
      id: 113,
      country_short_name: "KE",
      phone_code: 254,
      country_code: "+254",
    },
    {
      id: 114,
      country_short_name: "KI",
      phone_code: 686,
      country_code: "+686",
    },
    {
      id: 115,
      country_short_name: "KP",
      phone_code: 850,
      country_code: "+850",
    },
    {
      id: 116,
      country_short_name: "KR",
      phone_code: 82,
      country_code: "+82",
    },
    {
      id: 117,
      country_short_name: "KW",
      phone_code: 965,
      country_code: "+965",
    },
    {
      id: 118,
      country_short_name: "KG",
      phone_code: 996,
      country_code: "+996",
    },
    {
      id: 119,
      country_short_name: "LA",
      phone_code: 856,
      country_code: "+856",
    },
    {
      id: 120,
      country_short_name: "LV",
      phone_code: 371,
      country_code: "+371",
    },
    {
      id: 121,
      country_short_name: "LB",
      phone_code: 961,
      country_code: "+961",
    },
    {
      id: 122,
      country_short_name: "LS",
      phone_code: 266,
      country_code: "+266",
    },
    {
      id: 123,
      country_short_name: "LR",
      phone_code: 231,
      country_code: "+231",
    },
    {
      id: 124,
      country_short_name: "LY",
      phone_code: 218,
      country_code: "+218",
    },
    {
      id: 125,
      country_short_name: "LI",
      phone_code: 423,
      country_code: "+423",
    },
    {
      id: 126,
      country_short_name: "LT",
      phone_code: 370,
      country_code: "+370",
    },
    {
      id: 127,
      country_short_name: "LU",
      phone_code: 352,
      country_code: "+352",
    },
    {
      id: 128,
      country_short_name: "MO",
      phone_code: 853,
      country_code: "+853",
    },
    {
      id: 129,
      country_short_name: "MK",
      phone_code: 389,
      country_code: "+389",
    },
    {
      id: 130,
      country_short_name: "MG",
      phone_code: 261,
      country_code: "+261",
    },
    {
      id: 131,
      country_short_name: "MW",
      phone_code: 265,
      country_code: "+265",
    },
    {
      id: 132,
      country_short_name: "MY",
      phone_code: 60,
      country_code: "+60",
    },
    {
      id: 133,
      country_short_name: "MV",
      phone_code: 960,
      country_code: "+960",
    },
    {
      id: 134,
      country_short_name: "ML",
      phone_code: 223,
      country_code: "+223",
    },
    {
      id: 135,
      country_short_name: "MT",
      phone_code: 356,
      country_code: "+356",
    },
    {
      id: 137,
      country_short_name: "MH",
      phone_code: 692,
      country_code: "+692",
    },
    {
      id: 138,
      country_short_name: "MQ",
      phone_code: 596,
      country_code: "+596",
    },
    {
      id: 139,
      country_short_name: "MR",
      phone_code: 222,
      country_code: "+222",
    },
    {
      id: 140,
      country_short_name: "MU",
      phone_code: 230,
      country_code: "+230",
    },
    {
      id: 141,
      country_short_name: "YT",
      phone_code: 269,
      country_code: "+269",
    },
    {
      id: 142,
      country_short_name: "MX",
      phone_code: 52,
      country_code: "+52",
    },
    {
      id: 143,
      country_short_name: "FM",
      phone_code: 691,
      country_code: "+691",
    },
    {
      id: 144,
      country_short_name: "MD",
      phone_code: 373,
      country_code: "+373",
    },
    {
      id: 145,
      country_short_name: "MC",
      phone_code: 377,
      country_code: "+377",
    },
    {
      id: 146,
      country_short_name: "MN",
      phone_code: 976,
      country_code: "+976",
    },
    {
      id: 147,
      country_short_name: "MS",
      phone_code: 1664,
      country_code: "+1664",
    },
    {
      id: 148,
      country_short_name: "MA",
      phone_code: 212,
      country_code: "+212",
    },
    {
      id: 149,
      country_short_name: "MZ",
      phone_code: 258,
      country_code: "+258",
    },
    {
      id: 150,
      country_short_name: "MM",
      phone_code: 95,
      country_code: "+95",
    },
    {
      id: 151,
      country_short_name: "NA",
      phone_code: 264,
      country_code: "+264",
    },
    {
      id: 152,
      country_short_name: "NR",
      phone_code: 674,
      country_code: "+674",
    },
    {
      id: 153,
      country_short_name: "NP",
      phone_code: 977,
      country_code: "+977",
    },
    {
      id: 154,
      country_short_name: "AN",
      phone_code: 599,
      country_code: "+599",
    },
    {
      id: 155,
      country_short_name: "NL",
      phone_code: 31,
      country_code: "+31",
    },
    {
      id: 156,
      country_short_name: "NC",
      phone_code: 687,
      country_code: "+687",
    },
    {
      id: 157,
      country_short_name: "NZ",
      phone_code: 64,
      country_code: "+64",
    },
    {
      id: 158,
      country_short_name: "NI",
      phone_code: 505,
      country_code: "+505",
    },
    {
      id: 159,
      country_short_name: "NE",
      phone_code: 227,
      country_code: "+227",
    },
    {
      id: 160,
      country_short_name: "NG",
      phone_code: 234,
      country_code: "+234",
    },
    {
      id: 161,
      country_short_name: "NU",
      phone_code: 683,
      country_code: "+683",
    },
    {
      id: 162,
      country_short_name: "NF",
      phone_code: 672,
      country_code: "+672",
    },
    {
      id: 163,
      country_short_name: "MP",
      phone_code: 1670,
      country_code: "+1670",
    },
    {
      id: 164,
      country_short_name: "NO",
      phone_code: 47,
      country_code: "+47",
    },
    {
      id: 165,
      country_short_name: "OM",
      phone_code: 968,
      country_code: "+968",
    },
    {
      id: 166,
      country_short_name: "PK",
      phone_code: 92,
      country_code: "+92",
    },
    {
      id: 167,
      country_short_name: "PW",
      phone_code: 680,
      country_code: "+680",
    },
    {
      id: 168,
      country_short_name: "PS",
      phone_code: 970,
      country_code: "+970",
    },
    {
      id: 169,
      country_short_name: "PA",
      phone_code: 507,
      country_code: "+507",
    },
    {
      id: 170,
      country_short_name: "PG",
      phone_code: 675,
      country_code: "+675",
    },
    {
      id: 171,
      country_short_name: "PY",
      phone_code: 595,
      country_code: "+595",
    },
    {
      id: 172,
      country_short_name: "PE",
      phone_code: 51,
      country_code: "+51",
    },
    {
      id: 173,
      country_short_name: "PH",
      phone_code: 63,
      country_code: "+63",
    },
    {
      id: 174,
      country_short_name: "PN",
      phone_code: 0,
      country_code: "+0",
    },
    {
      id: 175,
      country_short_name: "PL",
      phone_code: 48,
      country_code: "+48",
    },
    {
      id: 176,
      country_short_name: "PT",
      phone_code: 351,
      country_code: "+351",
    },
    {
      id: 177,
      country_short_name: "PR",
      phone_code: 1787,
      country_code: "+1787",
    },
    {
      id: 178,
      country_short_name: "QA",
      phone_code: 974,
      country_code: "+974",
    },
    {
      id: 179,
      country_short_name: "RE",
      phone_code: 262,
      country_code: "+262",
    },
    {
      id: 180,
      country_short_name: "RO",
      phone_code: 40,
      country_code: "+40",
    },
    {
      id: 181,
      country_short_name: "RU",
      phone_code: 70,
      country_code: "+70",
    },
    {
      id: 182,
      country_short_name: "RW",
      phone_code: 250,
      country_code: "+250",
    },
    {
      id: 183,
      country_short_name: "SH",
      phone_code: 290,
      country_code: "+290",
    },
    {
      id: 184,
      country_short_name: "KN",
      phone_code: 1869,
      country_code: "+1869",
    },
    {
      id: 185,
      country_short_name: "LC",
      phone_code: 1758,
      country_code: "+1758",
    },
    {
      id: 186,
      country_short_name: "PM",
      phone_code: 508,
      country_code: "+508",
    },
    {
      id: 187,
      country_short_name: "VC",
      phone_code: 1784,
      country_code: "+1784",
    },
    {
      id: 188,
      country_short_name: "WS",
      phone_code: 684,
      country_code: "+684",
    },
    {
      id: 189,
      country_short_name: "SM",
      phone_code: 378,
      country_code: "+378",
    },
    {
      id: 190,
      country_short_name: "ST",
      phone_code: 239,
      country_code: "+239",
    },
    {
      id: 191,
      country_short_name: "SA",
      phone_code: 966,
      country_code: "+966",
    },
    {
      id: 192,
      country_short_name: "SN",
      phone_code: 221,
      country_code: "+221",
    },
    {
      id: 193,
      country_short_name: "RS",
      phone_code: 381,
      country_code: "+381",
    },
    {
      id: 194,
      country_short_name: "SC",
      phone_code: 248,
      country_code: "+248",
    },
    {
      id: 195,
      country_short_name: "SL",
      phone_code: 232,
      country_code: "+232",
    },
    {
      id: 196,
      country_short_name: "SG",
      phone_code: 65,
      country_code: "+65",
    },
    {
      id: 197,
      country_short_name: "SK",
      phone_code: 421,
      country_code: "+421",
    },
    {
      id: 198,
      country_short_name: "SI",
      phone_code: 386,
      country_code: "+386",
    },
    {
      id: 200,
      country_short_name: "SB",
      phone_code: 677,
      country_code: "+677",
    },
    {
      id: 201,
      country_short_name: "SO",
      phone_code: 252,
      country_code: "+252",
    },
    {
      id: 202,
      country_short_name: "ZA",
      phone_code: 27,
      country_code: "+27",
    },
    {
      id: 203,
      country_short_name: "GS",
      phone_code: 0,
      country_code: "+0",
    },
    {
      id: 204,
      country_short_name: "SS",
      phone_code: 211,
      country_code: "+211",
    },
    {
      id: 205,
      country_short_name: "ES",
      phone_code: 34,
      country_code: "+34",
    },
    {
      id: 206,
      country_short_name: "LK",
      phone_code: 94,
      country_code: "+94",
    },
    {
      id: 207,
      country_short_name: "SD",
      phone_code: 249,
      country_code: "+249",
    },
    {
      id: 208,
      country_short_name: "SR",
      phone_code: 597,
      country_code: "+597",
    },
    {
      id: 209,
      country_short_name: "SJ",
      phone_code: 47,
      country_code: "+47",
    },
    {
      id: 210,
      country_short_name: "SZ",
      phone_code: 268,
      country_code: "+268",
    },
    {
      id: 211,
      country_short_name: "SE",
      phone_code: 46,
      country_code: "+46",
    },
    {
      id: 212,
      country_short_name: "CH",
      phone_code: 41,
      country_code: "+41",
    },
    {
      id: 213,
      country_short_name: "SY",
      phone_code: 963,
      country_code: "+963",
    },
    {
      id: 214,
      country_short_name: "TW",
      phone_code: 886,
      country_code: "+886",
    },
    {
      id: 215,
      country_short_name: "TJ",
      phone_code: 992,
      country_code: "+992",
    },
    {
      id: 216,
      country_short_name: "TZ",
      phone_code: 255,
      country_code: "+255",
    },
    {
      id: 217,
      country_short_name: "TH",
      phone_code: 66,
      country_code: "+66",
    },
    {
      id: 218,
      country_short_name: "TG",
      phone_code: 228,
      country_code: "+228",
    },
    {
      id: 219,
      country_short_name: "TK",
      phone_code: 690,
      country_code: "+690",
    },
    {
      id: 220,
      country_short_name: "TO",
      phone_code: 676,
      country_code: "+676",
    },
    {
      id: 221,
      country_short_name: "TT",
      phone_code: 1868,
      country_code: "+1868",
    },
    {
      id: 222,
      country_short_name: "TN",
      phone_code: 216,
      country_code: "+216",
    },
    {
      id: 223,
      country_short_name: "TR",
      phone_code: 90,
      country_code: "+90",
    },
    {
      id: 224,
      country_short_name: "TM",
      phone_code: 7370,
      country_code: "+7370",
    },
    {
      id: 225,
      country_short_name: "TC",
      phone_code: 1649,
      country_code: "+1649",
    },
    {
      id: 226,
      country_short_name: "TV",
      phone_code: 688,
      country_code: "+688",
    },
    {
      id: 227,
      country_short_name: "UG",
      phone_code: 256,
      country_code: "+256",
    },
    {
      id: 228,
      country_short_name: "UA",
      phone_code: 380,
      country_code: "+380",
    },
    {
      id: 229,
      country_short_name: "AE",
      phone_code: 971,
      country_code: "+971",
    },
    {
      id: 231,
      country_short_name: "US",
      phone_code: 1,
      country_code: "+1",
    },
    {
      id: 232,
      country_short_name: "UM",
      phone_code: 1,
      country_code: "+1",
    },
    {
      id: 233,
      country_short_name: "UY",
      phone_code: 598,
      country_code: "+598",
    },
    {
      id: 234,
      country_short_name: "UZ",
      phone_code: 998,
      country_code: "+998",
    },
    {
      id: 235,
      country_short_name: "VU",
      phone_code: 678,
      country_code: "+678",
    },
    {
      id: 236,
      country_short_name: "VA",
      phone_code: 39,
      country_code: "+39",
    },
    {
      id: 237,
      country_short_name: "VE",
      phone_code: 58,
      country_code: "+58",
    },
    {
      id: 238,
      country_short_name: "VN",
      phone_code: 84,
      country_code: "+84",
    },
    {
      id: 239,
      country_short_name: "VG",
      phone_code: 1284,
      country_code: "+1284",
    },
    {
      id: 240,
      country_short_name: "VI",
      phone_code: 1340,
      country_code: "+1340",
    },
    {
      id: 241,
      country_short_name: "WF",
      phone_code: 681,
      country_code: "+681",
    },
    {
      id: 242,
      country_short_name: "EH",
      phone_code: 212,
      country_code: "+212",
    },
    {
      id: 243,
      country_short_name: "YE",
      phone_code: 967,
      country_code: "+967",
    },
    {
      id: 244,
      country_short_name: "YU",
      phone_code: 38,
      country_code: "+38",
    },
    {
      id: 245,
      country_short_name: "ZM",
      phone_code: 260,
      country_code: "+260",
    },
    {
      id: 246,
      country_short_name: "ZW",
      phone_code: 263,
      country_code: "+263",
    },
    {
      id: 247,
      country_short_name: "TBC",
      phone_code: 0,
      country_code: "+0",
    },
    {
      id: 249,
      country_short_name: "TBA",
      phone_code: 0,
      country_code: "",
    },
    {
      id: 250,
      country_short_name: "Kos",
      phone_code: 383,
      country_code: "",
    },
    {
      id: 251,
      country_short_name: "Mon",
      phone_code: 382,
      country_code: "",
    },
    {
      id: 252,
      country_short_name: "Nor",
      phone_code: 389,
      country_code: "",
    },
  ],
};
