export const allCountryCodes = {
  data: [
    {
      id: 1,
      name: "Afghanistan",
      short_name: "AF",
      phone_code: 93,
      dialing_code: "+93",
    },
    {
      id: 2,
      name: "Albania",
      short_name: "AL",
      phone_code: 355,
      dialing_code: "+355",
    },
    {
      id: 3,
      name: "Algeria",
      short_name: "AL",
      phone_code: 213,
      dialing_code: "+213",
    },
    {
      id: 4,
      name: "American Samoa",
      short_name: "AS",
      phone_code: 1684,
      dialing_code: "+1684",
    },
    {
      id: 5,
      name: "Andorra",
      short_name: "AD",
      phone_code: 376,
      dialing_code: "+376",
    },
    {
      id: 6,
      name: "Angola",
      short_name: "AO",
      phone_code: 244,
      dialing_code: "+244",
    },
    {
      id: 7,
      name: "Anguilla",
      short_name: "AI",
      phone_code: 1264,
      dialing_code: "+1264",
    },
    {
      id: 8,
      name: "Antarctica",
      short_name: "AQ",
      phone_code: 0,
      dialing_code: "+0",
    },
    {
      id: 9,
      name: "Antigua And Barbuda",
      short_name: "AG",
      phone_code: 1268,
      dialing_code: "+1268",
    },
    {
      id: 10,
      name: "Argentina",
      short_name: "AR",
      phone_code: 54,
      dialing_code: "+54",
    },
    {
      id: 11,
      name: "Armenia",
      short_name: "AM",
      phone_code: 374,
      dialing_code: "+374",
    },
    {
      id: 12,
      name: "Aruba",
      short_name: "AW",
      phone_code: 297,
      dialing_code: "+297",
    },
    {
      id: 13,
      name: "Australia",
      short_name: "AU",
      phone_code: 61,
      dialing_code: "+61",
    },
    {
      id: 14,
      name: "Austria",
      short_name: "AT",
      phone_code: 43,
      dialing_code: "+43",
    },
    {
      id: 15,
      name: "Azerbaijan",
      short_name: "AZ",
      phone_code: 994,
      dialing_code: "+994",
    },
    {
      id: 16,
      name: "Bahamas The",
      short_name: "BS",
      phone_code: 1242,
      dialing_code: "+1242",
    },
    {
      id: 17,
      name: "Bahrain",
      short_name: "BH",
      phone_code: 973,
      dialing_code: "+973",
    },
    {
      id: 18,
      name: "Bangladesh",
      short_name: "BD",
      phone_code: 880,
      dialing_code: "+880",
    },
    {
      id: 19,
      name: "Barbados",
      short_name: "BB",
      phone_code: 1246,
      dialing_code: "+1246",
    },
    {
      id: 20,
      name: "Belarus",
      short_name: "BY",
      phone_code: 375,
      dialing_code: "+375",
    },
    {
      id: 21,
      name: "Belgium",
      short_name: "BE",
      phone_code: 32,
      dialing_code: "+32",
    },
    {
      id: 22,
      name: "Belize",
      short_name: "BZ",
      phone_code: 501,
      dialing_code: "+501",
    },
    {
      id: 23,
      name: "Benin",
      short_name: "BJ",
      phone_code: 229,
      dialing_code: "+229",
    },
    {
      id: 24,
      name: "Bermuda",
      short_name: "BM",
      phone_code: 1441,
      dialing_code: "+1441",
    },
    {
      id: 25,
      name: "Bhutan",
      short_name: "BT",
      phone_code: 975,
      dialing_code: "+975",
    },
    {
      id: 26,
      name: "Bolivia",
      short_name: "BO",
      phone_code: 591,
      dialing_code: "+591",
    },
    {
      id: 27,
      name: "Bosnia and Herzegovina",
      short_name: "BA",
      phone_code: 387,
      dialing_code: "+387",
    },
    {
      id: 28,
      name: "Botswana",
      short_name: "BW",
      phone_code: 267,
      dialing_code: "+267",
    },
    {
      id: 29,
      name: "Bouvet Island",
      short_name: "BV",
      phone_code: 0,
      dialing_code: "+0",
    },
    {
      id: 30,
      name: "Brazil",
      short_name: "BR",
      phone_code: 55,
      dialing_code: "+55",
    },
    {
      id: 31,
      name: "British Indian Ocean Territory",
      short_name: "IO",
      phone_code: 246,
      dialing_code: "+246",
    },
    {
      id: 32,
      name: "Brunei",
      short_name: "BN",
      phone_code: 673,
      dialing_code: "+673",
    },
    {
      id: 33,
      name: "Bulgaria",
      short_name: "BG",
      phone_code: 359,
      dialing_code: "+359",
    },
    {
      id: 34,
      name: "Burkina Faso",
      short_name: "BF",
      phone_code: 226,
      dialing_code: "+226",
    },
    {
      id: 35,
      name: "Burundi",
      short_name: "BI",
      phone_code: 257,
      dialing_code: "+257",
    },
    {
      id: 36,
      name: "Cambodia",
      short_name: "KH",
      phone_code: 855,
      dialing_code: "+855",
    },
    {
      id: 37,
      name: "Cameroon",
      short_name: "CM",
      phone_code: 237,
      dialing_code: "+237",
    },
    {
      id: 38,
      name: "Canada",
      short_name: "CA",
      phone_code: 1,
      dialing_code: "+1",
    },
    {
      id: 39,
      name: "Cape Verde",
      short_name: "CV",
      phone_code: 238,
      dialing_code: "+238",
    },
    {
      id: 40,
      name: "Cayman Islands",
      short_name: "KY",
      phone_code: 1345,
      dialing_code: "+1345",
    },
    {
      id: 41,
      name: "Central African Republic",
      short_name: "CF",
      phone_code: 236,
      dialing_code: "+236",
    },
    {
      id: 42,
      name: "Chad",
      short_name: "TD",
      phone_code: 235,
      dialing_code: "+235",
    },
    {
      id: 43,
      name: "Chile",
      short_name: "CL",
      phone_code: 56,
      dialing_code: "+56",
    },
    {
      id: 44,
      name: "China",
      short_name: "CN",
      phone_code: 86,
      dialing_code: "+86",
    },
    {
      id: 45,
      name: "Christmas Island",
      short_name: "CX",
      phone_code: 61,
      dialing_code: "+61",
    },
    {
      id: 46,
      name: "Cocos (Keeling) Islands",
      short_name: "CC",
      phone_code: 672,
      dialing_code: "+672",
    },
    {
      id: 47,
      name: "Colombia",
      short_name: "CO",
      phone_code: 57,
      dialing_code: "+57",
    },
    {
      id: 48,
      name: "Comoros",
      short_name: "KM",
      phone_code: 269,
      dialing_code: "+269",
    },
    {
      id: 51,
      name: "Cook Islands",
      short_name: "CK",
      phone_code: 682,
      dialing_code: "+682",
    },
    {
      id: 52,
      name: "Costa Rica",
      short_name: "CR",
      phone_code: 506,
      dialing_code: "+506",
    },
    {
      id: 53,
      name: "Cote D'Ivoire (Ivory Coast)",
      short_name: "CI",
      phone_code: 225,
      dialing_code: "+225",
    },
    {
      id: 54,
      name: "Croatia (Hrvatska)",
      short_name: "HR",
      phone_code: 385,
      dialing_code: "+385",
    },
    {
      id: 55,
      name: "Cuba",
      short_name: "CU",
      phone_code: 53,
      dialing_code: "+53",
    },
    {
      id: 56,
      name: "Cyprus",
      short_name: "CY",
      phone_code: 357,
      dialing_code: "+357",
    },
    {
      id: 57,
      name: "Czech Republic",
      short_name: "CZ",
      phone_code: 420,
      dialing_code: "+420",
    },
    {
      id: 50,
      name: "Democratic Republic Of The Congo",
      short_name: "CD",
      phone_code: 242,
      dialing_code: "+242",
    },
    {
      id: 58,
      name: "Denmark",
      short_name: "DK",
      phone_code: 45,
      dialing_code: "+45",
    },
    {
      id: 59,
      name: "Djibouti",
      short_name: "DJ",
      phone_code: 253,
      dialing_code: "+253",
    },
    {
      id: 60,
      name: "Dominica",
      short_name: "DM",
      phone_code: 1767,
      dialing_code: "+1767",
    },
    {
      id: 61,
      name: "Dominican Republic",
      short_name: "DO",
      phone_code: 1809,
      dialing_code: "+1809",
    },
    {
      id: 62,
      name: "East Timor",
      short_name: "TP",
      phone_code: 670,
      dialing_code: "+670",
    },
    {
      id: 63,
      name: "Ecuador",
      short_name: "EC",
      phone_code: 593,
      dialing_code: "+593",
    },
    {
      id: 64,
      name: "Egypt",
      short_name: "EG",
      phone_code: 20,
      dialing_code: "+20",
    },
    {
      id: 65,
      name: "El Salvador",
      short_name: "SV",
      phone_code: 503,
      dialing_code: "+503",
    },
    {
      id: 66,
      name: "Equatorial Guinea",
      short_name: "GQ",
      phone_code: 240,
      dialing_code: "+240",
    },
    {
      id: 67,
      name: "Eritrea",
      short_name: "ER",
      phone_code: 291,
      dialing_code: "+291",
    },
    {
      id: 68,
      name: "Estonia",
      short_name: "EE",
      phone_code: 372,
      dialing_code: "+372",
    },
    {
      id: 69,
      name: "Ethiopia",
      short_name: "ET",
      phone_code: 251,
      dialing_code: "+251",
    },
    {
      id: 70,
      name: "External Territories of Australia",
      short_name: "XA",
      phone_code: 61,
      dialing_code: "+61",
    },
    {
      id: 71,
      name: "Falkland Islands",
      short_name: "FK",
      phone_code: 500,
      dialing_code: "+500",
    },
    {
      id: 72,
      name: "Faroe Islands",
      short_name: "FO",
      phone_code: 298,
      dialing_code: "+298",
    },
    {
      id: 73,
      name: "Fiji Islands",
      short_name: "FJ",
      phone_code: 679,
      dialing_code: "+679",
    },
    {
      id: 74,
      name: "Finland",
      short_name: "FI",
      phone_code: 358,
      dialing_code: "+358",
    },
    {
      id: 75,
      name: "France",
      short_name: "FR",
      phone_code: 33,
      dialing_code: "+33",
    },
    {
      id: 76,
      name: "French Guiana",
      short_name: "GF",
      phone_code: 594,
      dialing_code: "+594",
    },
    {
      id: 77,
      name: "French Polynesia",
      short_name: "PF",
      phone_code: 689,
      dialing_code: "+689",
    },
    {
      id: 78,
      name: "French Southern Territories",
      short_name: "TF",
      phone_code: 0,
      dialing_code: "+0",
    },
    {
      id: 79,
      name: "Gabon",
      short_name: "GA",
      phone_code: 241,
      dialing_code: "+241",
    },
    {
      id: 80,
      name: "Gambia The",
      short_name: "GM",
      phone_code: 220,
      dialing_code: "+220",
    },
    {
      id: 81,
      name: "Georgia",
      short_name: "GE",
      phone_code: 995,
      dialing_code: "+995",
    },
    {
      id: 82,
      name: "Germany",
      short_name: "DE",
      phone_code: 49,
      dialing_code: "+49",
    },
    {
      id: 83,
      name: "Ghana",
      short_name: "GH",
      phone_code: 233,
      dialing_code: "+233",
    },
    {
      id: 84,
      name: "Gibraltar",
      short_name: "GI",
      phone_code: 350,
      dialing_code: "+350",
    },
    {
      id: 85,
      name: "Greece",
      short_name: "GR",
      phone_code: 30,
      dialing_code: "+30",
    },
    {
      id: 86,
      name: "Greenland",
      short_name: "GL",
      phone_code: 299,
      dialing_code: "+299",
    },
    {
      id: 87,
      name: "Grenada",
      short_name: "GD",
      phone_code: 1473,
      dialing_code: "+1473",
    },
    {
      id: 88,
      name: "Guadeloupe",
      short_name: "GP",
      phone_code: 590,
      dialing_code: "+590",
    },
    {
      id: 89,
      name: "Guam",
      short_name: "GU",
      phone_code: 1671,
      dialing_code: "+1671",
    },
    {
      id: 90,
      name: "Guatemala",
      short_name: "GT",
      phone_code: 502,
      dialing_code: "+502",
    },
    {
      id: 91,
      name: "Guernsey and Alderney",
      short_name: "GG",
      phone_code: 44,
      dialing_code: "+44",
    },
    {
      id: 92,
      name: "Guinea",
      short_name: "GN",
      phone_code: 224,
      dialing_code: "+224",
    },
    {
      id: 93,
      name: "Guinea-Bissau",
      short_name: "GW",
      phone_code: 245,
      dialing_code: "+245",
    },
    {
      id: 94,
      name: "Guyana",
      short_name: "GY",
      phone_code: 592,
      dialing_code: "+592",
    },
    {
      id: 95,
      name: "Haiti",
      short_name: "HT",
      phone_code: 509,
      dialing_code: "+509",
    },
    {
      id: 96,
      name: "Heard and McDonald Islands",
      short_name: "HM",
      phone_code: 0,
      dialing_code: "+0",
    },
    {
      id: 97,
      name: "Honduras",
      short_name: "HN",
      phone_code: 504,
      dialing_code: "+504",
    },
    {
      id: 98,
      name: "Hong Kong S.A.R.",
      short_name: "HK",
      phone_code: 852,
      dialing_code: "+852",
    },
    {
      id: 99,
      name: "Hungary",
      short_name: "HU",
      phone_code: 36,
      dialing_code: "+36",
    },
    {
      id: 100,
      name: "Iceland",
      short_name: "IS",
      phone_code: 354,
      dialing_code: "+354",
    },
    {
      id: 101,
      name: "India",
      short_name: "IN",
      phone_code: 91,
      dialing_code: "+91",
    },
    {
      id: 102,
      name: "Indonesia",
      short_name: "ID",
      phone_code: 62,
      dialing_code: "+62",
    },
    {
      id: 103,
      name: "Iran",
      short_name: "IR",
      phone_code: 98,
      dialing_code: "+98",
    },
    {
      id: 104,
      name: "Iraq",
      short_name: "IQ",
      phone_code: 964,
      dialing_code: "+964",
    },
    {
      id: 105,
      name: "Ireland",
      short_name: "IE",
      phone_code: 353,
      dialing_code: "+353",
    },
    {
      id: 106,
      name: "Israel",
      short_name: "IL",
      phone_code: 972,
      dialing_code: "+972",
    },
    {
      id: 107,
      name: "Italy",
      short_name: "IT",
      phone_code: 39,
      dialing_code: "+39",
    },
    {
      id: 108,
      name: "Jamaica",
      short_name: "JM",
      phone_code: 1876,
      dialing_code: "+1876",
    },
    {
      id: 109,
      name: "Japan",
      short_name: "JP",
      phone_code: 81,
      dialing_code: "+81",
    },
    {
      id: 110,
      name: "Jersey",
      short_name: "GB",
      phone_code: 44,
      dialing_code: "+44",
    },
    {
      id: 111,
      name: "Jordan",
      short_name: "JO",
      phone_code: 962,
      dialing_code: "+962",
    },
    {
      id: 112,
      name: "Kazakhstan",
      short_name: "KZ",
      phone_code: 7,
      dialing_code: "+7",
    },
    {
      id: 113,
      name: "Kenya",
      short_name: "KE",
      phone_code: 254,
      dialing_code: "+254",
    },
    {
      id: 114,
      name: "Kiribati",
      short_name: "KI",
      phone_code: 686,
      dialing_code: "+686",
    },
    {
      id: 115,
      name: "Korea North",
      short_name: "KP",
      phone_code: 850,
      dialing_code: "+850",
    },
    {
      id: 116,
      name: "Korea South",
      short_name: "KR",
      phone_code: 82,
      dialing_code: "+82",
    },
    {
      id: 250,
      name: "Kosovo",
      short_name: "Kos",
      phone_code: 383,
      dialing_code: "",
    },
    {
      id: 117,
      name: "Kuwait",
      short_name: "KW",
      phone_code: 965,
      dialing_code: "+965",
    },
    {
      id: 118,
      name: "Kyrgyzstan",
      short_name: "KG",
      phone_code: 996,
      dialing_code: "+996",
    },
    {
      id: 119,
      name: "Laos",
      short_name: "LA",
      phone_code: 856,
      dialing_code: "+856",
    },
    {
      id: 120,
      name: "Latvia",
      short_name: "LV",
      phone_code: 371,
      dialing_code: "+371",
    },
    {
      id: 121,
      name: "Lebanon",
      short_name: "LB",
      phone_code: 961,
      dialing_code: "+961",
    },
    {
      id: 122,
      name: "Lesotho",
      short_name: "LS",
      phone_code: 266,
      dialing_code: "+266",
    },
    {
      id: 123,
      name: "Liberia",
      short_name: "LR",
      phone_code: 231,
      dialing_code: "+231",
    },
    {
      id: 124,
      name: "Libya",
      short_name: "LY",
      phone_code: 218,
      dialing_code: "+218",
    },
    {
      id: 125,
      name: "Liechtenstein",
      short_name: "LI",
      phone_code: 423,
      dialing_code: "+423",
    },
    {
      id: 126,
      name: "Lithuania",
      short_name: "LT",
      phone_code: 370,
      dialing_code: "+370",
    },
    {
      id: 127,
      name: "Luxembourg",
      short_name: "LU",
      phone_code: 352,
      dialing_code: "+352",
    },
    {
      id: 128,
      name: "Macau S.A.R.",
      short_name: "MO",
      phone_code: 853,
      dialing_code: "+853",
    },
    {
      id: 129,
      name: "Macedonia",
      short_name: "MK",
      phone_code: 389,
      dialing_code: "+389",
    },
    {
      id: 130,
      name: "Madagascar",
      short_name: "MG",
      phone_code: 261,
      dialing_code: "+261",
    },
    {
      id: 131,
      name: "Malawi",
      short_name: "MW",
      phone_code: 265,
      dialing_code: "+265",
    },
    {
      id: 132,
      name: "Malaysia",
      short_name: "MY",
      phone_code: 60,
      dialing_code: "+60",
    },
    {
      id: 133,
      name: "Maldives",
      short_name: "MV",
      phone_code: 960,
      dialing_code: "+960",
    },
    {
      id: 134,
      name: "Mali",
      short_name: "ML",
      phone_code: 223,
      dialing_code: "+223",
    },
    {
      id: 135,
      name: "Malta",
      short_name: "MT",
      phone_code: 356,
      dialing_code: "+356",
    },
    {
      id: 136,
      name: "Man (Isle of)",
      short_name: "GB",
      phone_code: 44,
      dialing_code: "+44",
    },
    {
      id: 137,
      name: "Marshall Islands",
      short_name: "MH",
      phone_code: 692,
      dialing_code: "+692",
    },
    {
      id: 138,
      name: "Martinique",
      short_name: "MQ",
      phone_code: 596,
      dialing_code: "+596",
    },
    {
      id: 139,
      name: "Mauritania",
      short_name: "MR",
      phone_code: 222,
      dialing_code: "+222",
    },
    {
      id: 140,
      name: "Mauritius",
      short_name: "MU",
      phone_code: 230,
      dialing_code: "+230",
    },
    {
      id: 141,
      name: "Mayotte",
      short_name: "YT",
      phone_code: 269,
      dialing_code: "+269",
    },
    {
      id: 142,
      name: "Mexico",
      short_name: "MX",
      phone_code: 52,
      dialing_code: "+52",
    },
    {
      id: 143,
      name: "Micronesia",
      short_name: "FM",
      phone_code: 691,
      dialing_code: "+691",
    },
    {
      id: 144,
      name: "Moldova",
      short_name: "MD",
      phone_code: 373,
      dialing_code: "+373",
    },
    {
      id: 145,
      name: "Monaco",
      short_name: "MC",
      phone_code: 377,
      dialing_code: "+377",
    },
    {
      id: 146,
      name: "Mongolia",
      short_name: "MN",
      phone_code: 976,
      dialing_code: "+976",
    },
    {
      id: 251,
      name: "Montenegro",
      short_name: "Mon",
      phone_code: 382,
      dialing_code: "",
    },
    {
      id: 147,
      name: "Montserrat",
      short_name: "MS",
      phone_code: 1664,
      dialing_code: "+1664",
    },
    {
      id: 148,
      name: "Morocco",
      short_name: "MA",
      phone_code: 212,
      dialing_code: "+212",
    },
    {
      id: 149,
      name: "Mozambique",
      short_name: "MZ",
      phone_code: 258,
      dialing_code: "+258",
    },
    {
      id: 150,
      name: "Myanmar",
      short_name: "MM",
      phone_code: 95,
      dialing_code: "+95",
    },
    {
      id: 151,
      name: "Namibia",
      short_name: "NA",
      phone_code: 264,
      dialing_code: "+264",
    },
    {
      id: 152,
      name: "Nauru",
      short_name: "NR",
      phone_code: 674,
      dialing_code: "+674",
    },
    {
      id: 153,
      name: "Nepal",
      short_name: "NP",
      phone_code: 977,
      dialing_code: "+977",
    },
    {
      id: 155,
      name: "Netherlands",
      short_name: "NL",
      phone_code: 31,
      dialing_code: "+31",
    },
    {
      id: 154,
      name: "Netherlands Antilles",
      short_name: "AN",
      phone_code: 599,
      dialing_code: "+599",
    },
    {
      id: 156,
      name: "New Caledonia",
      short_name: "NC",
      phone_code: 687,
      dialing_code: "+687",
    },
    {
      id: 157,
      name: "New Zealand",
      short_name: "NZ",
      phone_code: 64,
      dialing_code: "+64",
    },
    {
      id: 158,
      name: "Nicaragua",
      short_name: "NI",
      phone_code: 505,
      dialing_code: "+505",
    },
    {
      id: 159,
      name: "Niger",
      short_name: "NE",
      phone_code: 227,
      dialing_code: "+227",
    },
    {
      id: 160,
      name: "Nigeria",
      short_name: "NG",
      phone_code: 234,
      dialing_code: "+234",
    },
    {
      id: 161,
      name: "Niue",
      short_name: "NU",
      phone_code: 683,
      dialing_code: "+683",
    },
    {
      id: 162,
      name: "Norfolk Island",
      short_name: "NF",
      phone_code: 672,
      dialing_code: "+672",
    },
    {
      id: 252,
      name: "North Macedonia",
      short_name: "Nor",
      phone_code: 389,
      dialing_code: "",
    },
    {
      id: 163,
      name: "Northern Mariana Islands",
      short_name: "MP",
      phone_code: 1670,
      dialing_code: "+1670",
    },
    {
      id: 164,
      name: "Norway",
      short_name: "NO",
      phone_code: 47,
      dialing_code: "+47",
    },
    {
      id: 165,
      name: "Oman",
      short_name: "OM",
      phone_code: 968,
      dialing_code: "+968",
    },
    {
      id: 166,
      name: "Pakistan",
      short_name: "PK",
      phone_code: 92,
      dialing_code: "+92",
    },
    {
      id: 167,
      name: "Palau",
      short_name: "PW",
      phone_code: 680,
      dialing_code: "+680",
    },
    {
      id: 168,
      name: "Palestinian Territory Occupied",
      short_name: "PS",
      phone_code: 970,
      dialing_code: "+970",
    },
    {
      id: 169,
      name: "Panama",
      short_name: "PA",
      phone_code: 507,
      dialing_code: "+507",
    },
    {
      id: 170,
      name: "Papua new Guinea",
      short_name: "PG",
      phone_code: 675,
      dialing_code: "+675",
    },
    {
      id: 171,
      name: "Paraguay",
      short_name: "PY",
      phone_code: 595,
      dialing_code: "+595",
    },
    {
      id: 172,
      name: "Peru",
      short_name: "PE",
      phone_code: 51,
      dialing_code: "+51",
    },
    {
      id: 173,
      name: "Philippines",
      short_name: "PH",
      phone_code: 63,
      dialing_code: "+63",
    },
    {
      id: 174,
      name: "Pitcairn Island",
      short_name: "PN",
      phone_code: 0,
      dialing_code: "+0",
    },
    {
      id: 175,
      name: "Poland",
      short_name: "PL",
      phone_code: 48,
      dialing_code: "+48",
    },
    {
      id: 176,
      name: "Portugal",
      short_name: "PT",
      phone_code: 351,
      dialing_code: "+351",
    },
    {
      id: 177,
      name: "Puerto Rico",
      short_name: "PR",
      phone_code: 1787,
      dialing_code: "+1787",
    },
    {
      id: 178,
      name: "Qatar",
      short_name: "QA",
      phone_code: 974,
      dialing_code: "+974",
    },
    {
      id: 49,
      name: "Republic Of The Congo",
      short_name: "CG",
      phone_code: 242,
      dialing_code: "+242",
    },
    {
      id: 179,
      name: "Reunion",
      short_name: "RE",
      phone_code: 262,
      dialing_code: "+262",
    },
    {
      id: 180,
      name: "Romania",
      short_name: "RO",
      phone_code: 40,
      dialing_code: "+40",
    },
    {
      id: 181,
      name: "Russia",
      short_name: "RU",
      phone_code: 70,
      dialing_code: "+70",
    },
    {
      id: 182,
      name: "Rwanda",
      short_name: "RW",
      phone_code: 250,
      dialing_code: "+250",
    },
    {
      id: 183,
      name: "Saint Helena",
      short_name: "SH",
      phone_code: 290,
      dialing_code: "+290",
    },
    {
      id: 184,
      name: "Saint Kitts And Nevis",
      short_name: "KN",
      phone_code: 1869,
      dialing_code: "+1869",
    },
    {
      id: 185,
      name: "Saint Lucia",
      short_name: "LC",
      phone_code: 1758,
      dialing_code: "+1758",
    },
    {
      id: 186,
      name: "Saint Pierre and Miquelon",
      short_name: "PM",
      phone_code: 508,
      dialing_code: "+508",
    },
    {
      id: 187,
      name: "Saint Vincent And The Grenadines",
      short_name: "VC",
      phone_code: 1784,
      dialing_code: "+1784",
    },
    {
      id: 188,
      name: "Samoa",
      short_name: "WS",
      phone_code: 684,
      dialing_code: "+684",
    },
    {
      id: 189,
      name: "San Marino",
      short_name: "SM",
      phone_code: 378,
      dialing_code: "+378",
    },
    {
      id: 190,
      name: "Sao Tome and Principe",
      short_name: "ST",
      phone_code: 239,
      dialing_code: "+239",
    },
    {
      id: 191,
      name: "Saudi Arabia",
      short_name: "SA",
      phone_code: 966,
      dialing_code: "+966",
    },
    {
      id: 248,
      name: "Scotland",
      short_name: "Sco",
      phone_code: 44,
      dialing_code: "",
    },
    {
      id: 192,
      name: "Senegal",
      short_name: "SN",
      phone_code: 221,
      dialing_code: "+221",
    },
    {
      id: 193,
      name: "Serbia",
      short_name: "RS",
      phone_code: 381,
      dialing_code: "+381",
    },
    {
      id: 194,
      name: "Seychelles",
      short_name: "SC",
      phone_code: 248,
      dialing_code: "+248",
    },
    {
      id: 195,
      name: "Sierra Leone",
      short_name: "SL",
      phone_code: 232,
      dialing_code: "+232",
    },
    {
      id: 196,
      name: "Singapore",
      short_name: "SG",
      phone_code: 65,
      dialing_code: "+65",
    },
    {
      id: 197,
      name: "Slovakia",
      short_name: "SK",
      phone_code: 421,
      dialing_code: "+421",
    },
    {
      id: 198,
      name: "Slovenia",
      short_name: "SI",
      phone_code: 386,
      dialing_code: "+386",
    },
    {
      id: 199,
      name: "Smaller Territories of the UK",
      short_name: "GB",
      phone_code: 44,
      dialing_code: "+44",
    },
    {
      id: 200,
      name: "Solomon Islands",
      short_name: "SB",
      phone_code: 677,
      dialing_code: "+677",
    },
    {
      id: 201,
      name: "Somalia",
      short_name: "SO",
      phone_code: 252,
      dialing_code: "+252",
    },
    {
      id: 202,
      name: "South Africa",
      short_name: "ZA",
      phone_code: 27,
      dialing_code: "+27",
    },
    {
      id: 203,
      name: "South Georgia",
      short_name: "GS",
      phone_code: 0,
      dialing_code: "+0",
    },
    {
      id: 204,
      name: "South Sudan",
      short_name: "SS",
      phone_code: 211,
      dialing_code: "+211",
    },
    {
      id: 205,
      name: "Spain",
      short_name: "ES",
      phone_code: 34,
      dialing_code: "+34",
    },
    {
      id: 206,
      name: "Sri Lanka",
      short_name: "LK",
      phone_code: 94,
      dialing_code: "+94",
    },
    {
      id: 207,
      name: "Sudan",
      short_name: "SD",
      phone_code: 249,
      dialing_code: "+249",
    },
    {
      id: 208,
      name: "Suriname",
      short_name: "SR",
      phone_code: 597,
      dialing_code: "+597",
    },
    {
      id: 209,
      name: "Svalbard And Jan Mayen Islands",
      short_name: "SJ",
      phone_code: 47,
      dialing_code: "+47",
    },
    {
      id: 210,
      name: "Swaziland",
      short_name: "SZ",
      phone_code: 268,
      dialing_code: "+268",
    },
    {
      id: 211,
      name: "Sweden",
      short_name: "SE",
      phone_code: 46,
      dialing_code: "+46",
    },
    {
      id: 212,
      name: "Switzerland",
      short_name: "CH",
      phone_code: 41,
      dialing_code: "+41",
    },
    {
      id: 213,
      name: "Syria",
      short_name: "SY",
      phone_code: 963,
      dialing_code: "+963",
    },
    {
      id: 214,
      name: "Taiwan",
      short_name: "TW",
      phone_code: 886,
      dialing_code: "+886",
    },
    {
      id: 215,
      name: "Tajikistan",
      short_name: "TJ",
      phone_code: 992,
      dialing_code: "+992",
    },
    {
      id: 216,
      name: "Tanzania",
      short_name: "TZ",
      phone_code: 255,
      dialing_code: "+255",
    },
    {
      id: 249,
      name: "TBA",
      short_name: "TBA",
      phone_code: 0,
      dialing_code: "",
    },
    {
      id: 247,
      name: "TBC",
      short_name: "TBC",
      phone_code: 0,
      dialing_code: "+0",
    },
    {
      id: 217,
      name: "Thailand",
      short_name: "TH",
      phone_code: 66,
      dialing_code: "+66",
    },
    {
      id: 218,
      name: "Togo",
      short_name: "TG",
      phone_code: 228,
      dialing_code: "+228",
    },
    {
      id: 219,
      name: "Tokelau",
      short_name: "TK",
      phone_code: 690,
      dialing_code: "+690",
    },
    {
      id: 220,
      name: "Tonga",
      short_name: "TO",
      phone_code: 676,
      dialing_code: "+676",
    },
    {
      id: 221,
      name: "Trinidad And Tobago",
      short_name: "TT",
      phone_code: 1868,
      dialing_code: "+1868",
    },
    {
      id: 222,
      name: "Tunisia",
      short_name: "TN",
      phone_code: 216,
      dialing_code: "+216",
    },
    {
      id: 223,
      name: "Turkey",
      short_name: "TR",
      phone_code: 90,
      dialing_code: "+90",
    },
    {
      id: 224,
      name: "Turkmenistan",
      short_name: "TM",
      phone_code: 7370,
      dialing_code: "+7370",
    },
    {
      id: 225,
      name: "Turks And Caicos Islands",
      short_name: "TC",
      phone_code: 1649,
      dialing_code: "+1649",
    },
    {
      id: 226,
      name: "Tuvalu",
      short_name: "TV",
      phone_code: 688,
      dialing_code: "+688",
    },
    {
      id: 227,
      name: "Uganda",
      short_name: "UG",
      phone_code: 256,
      dialing_code: "+256",
    },
    {
      id: 228,
      name: "Ukraine",
      short_name: "UA",
      phone_code: 380,
      dialing_code: "+380",
    },
    {
      id: 229,
      name: "United Arab Emirates",
      short_name: "AE",
      phone_code: 971,
      dialing_code: "+971",
    },
    {
      id: 230,
      name: "United Kingdom",
      short_name: "GB",
      phone_code: 44,
      dialing_code: "+44",
    },
    {
      id: 231,
      name: "United States",
      short_name: "US",
      phone_code: 1,
      dialing_code: "+1",
    },
    {
      id: 232,
      name: "United States Minor Outlying Islands",
      short_name: "UM",
      phone_code: 1,
      dialing_code: "+1",
    },
    {
      id: 233,
      name: "Uruguay",
      short_name: "UY",
      phone_code: 598,
      dialing_code: "+598",
    },
    {
      id: 234,
      name: "Uzbekistan",
      short_name: "UZ",
      phone_code: 998,
      dialing_code: "+998",
    },
    {
      id: 235,
      name: "Vanuatu",
      short_name: "VU",
      phone_code: 678,
      dialing_code: "+678",
    },
    {
      id: 236,
      name: "Vatican City State (Holy See)",
      short_name: "VA",
      phone_code: 39,
      dialing_code: "+39",
    },
    {
      id: 237,
      name: "Venezuela",
      short_name: "VE",
      phone_code: 58,
      dialing_code: "+58",
    },
    {
      id: 238,
      name: "Vietnam",
      short_name: "VN",
      phone_code: 84,
      dialing_code: "+84",
    },
    {
      id: 239,
      name: "Virgin Islands (British)",
      short_name: "VG",
      phone_code: 1284,
      dialing_code: "+1284",
    },
    {
      id: 240,
      name: "Virgin Islands (US)",
      short_name: "VI",
      phone_code: 1340,
      dialing_code: "+1340",
    },
    {
      id: 241,
      name: "Wallis And Futuna Islands",
      short_name: "WF",
      phone_code: 681,
      dialing_code: "+681",
    },
    {
      id: 242,
      name: "Western Sahara",
      short_name: "EH",
      phone_code: 212,
      dialing_code: "+212",
    },
    {
      id: 243,
      name: "Yemen",
      short_name: "YE",
      phone_code: 967,
      dialing_code: "+967",
    },
    {
      id: 244,
      name: "Yugoslavia",
      short_name: "YU",
      phone_code: 38,
      dialing_code: "+38",
    },
    {
      id: 245,
      name: "Zambia",
      short_name: "ZM",
      phone_code: 260,
      dialing_code: "+260",
    },
    {
      id: 246,
      name: "Zimbabwe",
      short_name: "ZW",
      phone_code: 263,
      dialing_code: "+263",
    },
  ],
};
