export const ADD_WALLET_POPUP = "ADD_WALLET_POPUP";
export const CONFIRM_PURCHASE_POPUP = "CONFIRM_PURCHASE_POPUP";
export const UPDATE_NOTIFICATION_COUNT = "UPDATE_NOTIFICATION_COUNT";
export const SHOW_FULL_DISPLAY = "SHOW_FULL_DISPLAY";
export const FETCH_USER_ROLES = "FETCH_USER_ROLES";
export const USER_ACCESS_ROUTES = "USER_ACCESS_ROUTES";
export const GET_KYC_STATUS = "GET_KYC_STATUS";
