export const ADD_WALLET_POPUP = "ADD_WALLET_POPUP";
export const CONFIRM_PURCHASE_POPUP = "CONFIRM_PURCHASE_POPUP";
export const UPDATE_NOTIFICATION_COUNT = "UPDATE_NOTIFICATION_COUNT";
export const SHOW_FULL_DISPLAY = "SHOW_FULL_DISPLAY";
